config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'portfolio#index'
  resources :journals
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/journal.rb
class Journal < ApplicationRecord
    validates :title, presence: true, length: {minimum: 4, maximum: 20}
    validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController

    before_action :set_journal, only: [:show, :edit, :update, :destroy]

    def show
    end

    def index
        @journals = Journal.all
    end

    def create
        @journal = Journal.new(journal_params)
        if @journal.save
            flash[:notice] = "Journal was saved in the database"
            redirect_to @journal
        else
            render 'new'
        end
    end

    def new
        @journal = Journal.new
    end

    def edit
    end

    def update
        if @journal.update(journal_params)
            flash[:notice] = "Journal updated"
            redirect_to @journal
        else
            render 'edit'
        end
    end

    def destroy
        @journal.destroy
        redirect_to journals_path
    end

    private
    def set_journal
        @journal = Journal.find(params[:id])
    end

    def journal_params
        params.require(:journal).permit(:title, :description)
    end

end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/journals/_form.html.erb
<% if @journal.errors.any? %>
<h2> Sorry, You know the drill, these errors prevented it </h2>
<ul>
    <% @journal.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul>
<% end %>

<%= form_with(model: @journal, local:true) do |f| %>

<p>
    <%= f.label :title %>
    <br>
    <%= f.text_field :title %>
</p>

<p>
    <%= f.label :description %>
    <br>
    <%= f.text_area :description %>
</p>


<p>
    <%= f.submit %>
</p>
<% end %>

app/views/journals/edit.html.erb
<h1> Edit Your Entry </h1>

<%= render 'form' %>

<%= link_to 'Journal Lisings', journals_path %>

app/views/journals/index.html.erb
<h1> All your Journals </h1>

<%= link_to 'Create New Entry', new_journal_path %>
<br>
<hr>

<table>
    <thead>
        <tr>
            <th>Date</th>
            <th>Title</th>
            <th colspan="3">Actions</th>
        </tr>
    </thead>

    <tbody>
        <% @journals.each do |journal| %>
        <tr>
            <td><%= journal.created_at %> </td>
            <td><%= journal.title %> </td>
            <td><%= link_to 'View', journal_path(journal.id) %></td>
            <td><%= link_to 'Update', edit_journal_path(journal.id) %></td>
            <td><%= link_to 'Delete', journal_path(journal.id), method: :delete, data: {confirm: "Are you sure you wanna delete this record"} %></td>

        </tr>
        <% end %>
    </tbody>
</table>

app/views/journals/new.html.erb
<h1> Create Your Entry </h1>

<%= render 'form' %>

<%= link_to 'Journal Lisings', journals_path %>

app/views/journals/show.html.erb
<h1> This is your Journal </h1>
<p><strong>Date: </strong> <%= @journal.created_at %> </p>
<p><strong>Title: </strong><%= @journal.title %></p>
<p><strong>Entry: </strong><%= @journal.description %></p>

<%= link_to 'Edit', edit_journal_path(@journal.id) %> |
<%= link_to 'Delete', journal_path(@journal.id), method: :delete, data: {confirm: "Are you sure you wanna delete this record"} %> |
<%= link_to 'Journal Lisings', journals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title || "Rishabh" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>